### ISSUE TITLE
Implement extra white space removal from the user's input

### ISSUE THREAD

**Issue by itsmdasifraza** [Susmita-Dey/TextUtils#11]
In this feature, I will remove extra white space from the user's input:

Example input:
![Screenshot (191)](https://user-images.githubusercontent.com/58258334/193313355-9ed5d45f-665b-42ea-8fba-d4e12826ce58.png)

Example output:
Lorem Ipsum is simply dummy text of the printing and typesetting industry

**Comment by Susmita-Dey** [comment]
@itsmdasifraza Go ahead
