### ISSUE TITLE
Implement feature secure password generator

### ISSUE THREAD

**Issue by itsmdasifraza** [Susmita-Dey/TextUtils#12]
I will add a button which will generate 15 letter secure password using alphabets, numbers and special characters.
Output will be like this regular expression: **el75m);23^7@NQL**

**Comment by Susmita-Dey** [comment]
@itsmdasifraza It would a password generator then. But here we are working with text only.

**Comment by itsmdasifraza** [comment]
> @itsmdasifraza It would a password generator then. But here we are working with text only.

Actually password is also a set of characters, we can say that password is a complex text, I don't think this small password generator feature needs a separate project. please share your view @Susmita-Dey .
