### ISSUE TITLE
Make "Stop now" and "Listen now" into one button.

### ISSUE THREAD

**Issue by delivey** [Susmita-Dey/TextUtils#29]
Stop now would appear instead of Listen Now, when text is being played. And when audio playback is stopped, Listen Now would appear instead of Stop now.

Let me know if this is a feature you'd like added, if so, assign it to me.

**Comment by Susmita-Dey** [comment]
@delivey Go ahead. I guess this is for hacktoberfest

**Comment by delivey** [comment]
Finished.

PR: #36
