### ISSUE TITLE
Replace "Enable Dark Mode" Text in NavBar with Icons

### ISSUE THREAD

**Issue by EshaanAgg** [Susmita-Dey/TextUtils#3]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/96648934/192690213-63fda0bf-b8e9-420d-a0bc-cf356c5f810f.png">
Currently, the dark mode heading is statically set to "Enable Dark Mode".
It would be better if the heading is changed with the mode, i.e. "Switch to Dark Mode" when in light mode, and "Switch to Light Mode" when in dark mode.

**Comment by EshaanAgg** [comment]
@Susmita-Dey 
I would like to work on this issue. Please assign it to me.

**Comment by Susmita-Dey** [comment]
@EshaanAgg Instead of that can you add something like sun and moon which will change according to the theme.

**Comment by EshaanAgg** [comment]
Sure. I'll try to implement this.

**Comment by Susmita-Dey** [comment]
> Sure. I'll try to implement this.

Change the issue title then

**Comment by ReallyAnkit** [comment]
Can U also assign me this ?
I would like to contribute to it ! I am a beginner but I think I can perform this.

**Comment by Susmita-Dey** [comment]
@ReallyAnkit PR has already been made
