### ISSUE TITLE
Add confirm alert before clear text

### ISSUE THREAD

**Issue by shubhamdarwante2301** [Susmita-Dey/TextUtils#33]
If user by mistake clicked on clear text, then their work gets deleted.
so before deleting the text we can add a "confirm" box.
![Screenshot (160)](https://user-images.githubusercontent.com/79241232/193407578-be094d92-fe0b-4f90-8bc5-de50c0d731bb.png)
if the user clicks on ok then only text will be deleted,
otherwise, text remains the same.

**Comment by KaptainCS3** [comment]
!assign

**Comment by shubhamdarwante2301** [comment]
I made a PR #35 for this issue please review it

**Comment by shubhamdarwante2301** [comment]
I submitted PR #35 for this issue please review it
