### ISSUE TITLE
Feature: Convert to Titlecase

### ISSUE THREAD

**Issue by EshaanAgg** [Susmita-Dey/TextUtils#4]
Add a convert to [Titlecase ](https://en.wikipedia.org/wiki/Title_case) button (alongside Uppercase and Lowercase).
I would like to be assigned this issue. 
@Susmita-Dey

**Comment by Susmita-Dey** [comment]
@EshaanAgg Is it a hacktoberfest contribution?

**Comment by EshaanAgg** [comment]
Yes. I was hoping to work on this project under Hacktoberfest.

**Comment by Susmita-Dey** [comment]
> Yes. I was hoping to work on this project under Hacktoberfest. 

Okay go ahead
