### ISSUE TITLE
To improve the UI of Navbar

### ISSUE THREAD

**Issue by Kirankp25** [Susmita-Dey/TextUtils#45]
I would like to
 create a button for home and about us tab
havor effect
to add logo at left-hand top side near "TextUtils"
pls assign me this issue
![Screenshot (311)](https://user-images.githubusercontent.com/87818185/193472460-d743f435-1127-408c-9fb6-373e6d5d6bd7.png)
e

**Comment by Susmita-Dey** [comment]
@Kirankp25 For Home and About, buttons are not needed. Instead you can add hover effects to them.

**Comment by Kirankp25** [comment]
ok
