### ISSUE TITLE
Improve UI for toggle button

### ISSUE THREAD

**Issue by bhattabhi013** [Susmita-Dey/TextUtils#46]
What:
Instead of the 'enable dark mode' title, we should add the 'dark mode and 'right mode' titles on the left and right sides respectively. 

Screenshot:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/47862474/193477605-b29e1168-949d-49ea-bcdd-c556569af3b7.png">

**Comment by Susmita-Dey** [comment]
@bhattabhi013 A PR is already there.
