### ISSUE TITLE
Feature Add  Currency Converter

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Susmita-Dey/TextUtils#47]

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by slim-codes** [comment]
@AnshuPathak-88825 
Please don't open blank issues. Describe what this feature is about and why it's relevant. 
Your issues and PR's should be **meaningful** and **valuable**

**Comment by AnshuPathak-88825** [comment]
oh ok this  feature is all about to  convert one currency to another currency

**Comment by Susmita-Dey** [comment]
@slim-codes @AnshuPathak-88825 We're working with text here not making any calculators.

**Comment by slim-codes** [comment]
@Susmita-Dey 
I did not open this issue. Just wanted to point that out
