### ISSUE TITLE
adding logo to readme.md

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/TextUtils#49]

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Logo is not made for this. The **`T`** shaped was generated from a tool.

**Comment by bhattabhi013** [comment]
Can I work on this? 
I've also made a logo.
<img width="182" alt="image" src="https://user-images.githubusercontent.com/47862474/193631001-0d734fcc-f936-46d5-baef-24460e290026.png">

**Comment by Vanshiii203** [comment]
> @Vanshiii203 Logo is not made for this. The **`T`** shaped was generated from a tool.

I can design a logo first

**Comment by Vanshiii203** [comment]
@Susmita-Dey 
![logo](https://user-images.githubusercontent.com/94471189/193782622-db0071f8-122e-4909-83a8-fe5da257febc.png)
