### ISSUE TITLE
Add Issue template

### ISSUE THREAD

**Issue by bhattabhi013** [Susmita-Dey/TextUtils#52]
Add issue template for the project.
I have something like this in my mind.
<img width="537" alt="image" src="https://user-images.githubusercontent.com/47862474/193518891-22c5b6b6-c583-4b22-91ef-42af212ae93d.png">

**Comment by Susmita-Dey** [comment]
@bhattabhi013 Good idea. Go ahead

**Comment by Susmita-Dey** [comment]
@bhattabhi013 Duplicate issue. Check #48
