### ISSUE TITLE
Feature: Strip given text

### ISSUE THREAD

**Issue by Rohan-G** [Susmita-Dey/TextUtils#7]
Remove extra spaces from the beginning, end and in between words of given text

**Comment by Rohan-G** [comment]
Could I work on adding this feature?

**Comment by Susmita-Dey** [comment]
@Rohan-G Isn't it a duplicate issue? 
Also, can you share a ss?

**Comment by Rohan-G** [comment]
oh someone posted it after. My bad, I'll try to find something else
