### ISSUE TITLE
Change in text Dark mode to light

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Susmita-Dey/TextUtils#8]
![image](https://user-images.githubusercontent.com/78332454/193228342-54d142aa-d8ca-43d3-8c1e-bf0a27f1d98d.png)
I'm already in dark mode but it is showing me enable dark mode . I want to made changes if I'm in dark mode then text should be enable light and if i'm in light mode then text should be dark mode . The text should be change according modes

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 Go ahead

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 don't work on this. A PR is already there
