### ISSUE TITLE
Having an undo and redo option when using different functions

### ISSUE THREAD

**Issue by Ts-A** [Susmita-Dey/TextUtils#84]
### Undo/ Redo Action
Functionality to add **redo** and **undo** that would keep track of the actions implemented on the text, if one wanted to trace back. Can you assign this task to me?

**Comment by Susmita-Dey** [comment]
@Ts-A If a person does `Ctrl+Z`, the undo works fine. Are you thinking about having the undo redo button to provide users with the option of undo redo actions like recalling actions?

**Comment by Ts-A** [comment]
Yes.
