### ISSUE TITLE
Clean Code Enforcement

### ISSUE THREAD

**Issue by Ts-A** [Susmita-Dey/TextUtils#88]
#### 1. Migrating from using props and useState -> useReducer + useContext or @reduxjs/toolkit

> Global state management and better handling of data
> Avoid sending props all the way down the DOM structure, as it would become cumbersome if app requires future updates
> Better handling of side effects, if need be in future updates, when you can save the text to a server / cloud.

#### 2. Making different parts of the code to re-usable components and/or create custom hooks like button components in [TextForm.js](https://github.com/Susmita-Dey/TextUtils/blob/main/src/components/TextForm.js).

> Makes the future development process faster
> Easy to debug
> Improves the structure of the code

**Comment by Ts-A** [comment]
Any preference between useReducer or @reduxjs/toolkit? Which one would like to have?

**Comment by Susmita-Dey** [comment]
@Ts-A Add the best one
